title: "jekyll-shell-theme"
description: "This is a preview of jekyll-shell-theme."
github_username: tareqdandachi
baseurl: "/jekyll-shell-theme"
url: "tareqdandachi.github.io"

plugins:
  - jemoji

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
